name: 触发版本号更新
on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  send-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        run: |
          if [ "${{ github.repository }}" != "Class-Widgets/Class-Widgets" ]; then
            echo "[DEBUG] 工作流不在主仓库"
            exit 1
          fi

      - name: Trigger Repo Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GH_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"event_type\": \"update-version\"}" \
               https://api.github.com/repos/Class-Widgets/official_website/dispatches
